site_name: NextITS

site_author: Vladimir Mikryukov, Kessy Abarenkov
site_description: A pipeline for metabarcoding fungi and other eukaryotes with full-length ITS sequenced with PacBio.
copyright: "Copyright © 2022 Vladimir Mikryukov. All rights reserved."

site_url: https://Next-ITS.github.io/
repo_url: https://github.com/vmikk/NextITS

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/NextITS_logo.webp
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  features:

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - toc:
      permalink: True
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'Introduction':         'index.md'
  - 'Installation':         'installation.md'
  - 'Basic Usage':          'usage.md'
